name: wyvern_notes
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.10.0
  firebase_auth: ^6.5.2
  cloud_firestore: ^6.5.0
  flutter_svg: ^2.3.0
  pdf: ^3.12.0
  printing: ^5.14.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:

  uses-material-design: true

  assets:
    - assets/images/wyvern_logo.svg
    - assets/icons/wyvern_launcher_icon.png
